name: waitero
description: Waitero is a smart ordering system to be implemented at coffee shops or other similar.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^0.3.2
  auto_route: ^0.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.7.3
  auto_route_generator: ^0.2.2

flutter:
  uses-material-design: true
