name: waitero
description: Waitero is a smart ordering system to be implemented at coffee shops or other similar.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_route: ^0.2.2
  provider: ^4.0.2
  image_picker: ^0.6.3+1
  path: ^1.6.4
  firebase_core: ^0.4.3+2
  firebase_analytics: ^5.0.2
  cloud_firestore: ^0.13.0+1
  firebase_storage: ^3.1.1
  path_provider: ^1.5.1
  image: 2.1.4
  uuid: ^2.0.4
  cached_network_image: ^2.0.0
  outline_material_icons: ^0.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.7.3
  auto_route_generator: ^0.2.2

flutter:
  uses-material-design: true

  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/icon_fonts/custom_icons.ttf
    - family: Diodrum
      fonts:
        - asset: assets/fonts/Diodrum-Semibold.ttf
          weight: 600
